name: Deploy

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 
      - name: SSH into EC2 Instance
        env:
          HOSTNAME: ${{ secrets.SSH_DOMAIN }}
          USER_NAME: ${{ secrets.USER_NAME }}
          PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          
          
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -T -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} << EOF
            cd /home/ec2-user/${REPO}
            sh scripts/destroy_dev.sh
            sh scripts/start_dev.sh
          EOF
